version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: terapiamental-mongo
    networks:
      - terapiamental_api_network
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - $HOME/data/terapiamentaldb:/data/db

    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_ROOT
      MONGO_INITDB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $DB_NAME
    ports:
      - "$DB_PORT:$DB_PORT"

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: terapiamental-mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - terapiamental_api_network
    ports:
      - "8081:3200"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_ROOT
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo
    env_file:
      - .env
    links:
      - mongo

  terapiamental:
    container_name: terapiamental-api-core
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - terapiamental_api_network
    command: yarn dev # overrides CMD from dockerfile

networks:
  terapiamental_api_network:
    driver: bridge
