version: "3.9"

services:
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   container_name: terapiamental-mongo
  #   networks:
  #     - terapiamental_api_network
  #   volumes:
  #     - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  #     - $HOME/data/terapiamentaldb:/data/db

  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: $DB_ROOT
  #     MONGO_INITDB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
  #     MONGO_INITDB_DATABASE: $DB_NAME
  #   ports:
  #     - "$DB_PORT:$DB_PORT"

  # mongo-express:
  #   image: mongo-express:1.0.2-20-alpine3.19
  #   container_name: terapiamental-mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   networks:
  #     - terapiamental_api_network
  #   ports:
  #     - "8081:3200"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_ROOT
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_ROOT_PASSWORD
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #   env_file:
  #     - .env
  #   links:
  #     - mongo
  postgres:
    container_name: terapiamental-postgres
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

    networks:
      - terapiamental_api_network
    volumes:
      - $HOME/data/postgresql/terapiamental:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"

  # mysql:
  #   image: mysql:8.0
  #   restart: always
  #   container_name: terapiamental-mysql
  #   networks:
  #     - terapiamental_api_network
  #   volumes:
  #     - $HOME/data/mysql/terapiamental:/var/lib/mysql
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
  #     MYSQL_DATABASE: $DB_NAME
  #     MYSQL_USER: $DB_USER
  #     MYSQL_PASSWORD: $DB_PASSWORD
  #   ports:
  #     - "$DB_PORT:$DB_PORT"

  adminer:
    image: adminer:4.8.1
    container_name: terapiamental-adminer
    depends_on:
      # - mysql
      - postgres
    networks:
      - terapiamental_api_network
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: galkaev
    env_file:
      - .env

  terapiamental:
    container_name: terapiamental-api-core
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      # - mongo
      # - mysql
      - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - terapiamental_api_network
    command: yarn dev # overrides CMD from dockerfile

networks:
  terapiamental_api_network:
    driver: bridge
